[project]
name = "skgif-spec-merger"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.12",
    "httpx>=0.28.1",
    "pyyaml>=6.0.2",
    "toml>=0.10.2",
    "uvicorn>=0.34.2",
]

[api]
core_folder = "merge/API/core"
#core_version = "1.1.3"
#core_file = "skg-if-openapi.yaml"
core_fetching_url = "https://github.com/skg-if/api/openapi/ver/{version}/{filename}"
ext_folder = "merge/API/ext"

timeout = 60

[test]
query_url = "http://localhost:8000/api/ver/1.1.3/skg-if-openapi.yaml?ext=foo&ext=bar"