[api]
core_folder = "merge/API/core"
# Production URL
core_fetching_url = "https://w3id.org/skg-if/api/{version}/{filename}"
ext_folder = "merge/API/ext"
output_folder = "merge/API/output"

[api.ext]
ext_postfix = [".yaml", ".yml"]

[cache]
sqlite_file = "cache.db"

[test]
# Local URL for testing
#core_fetching_url = "http://nginx/{version}/{filename}"
query_url = "http://localhost:8000/api/ver/1.1.3/skg-if-openapi.yaml?ext=foo&ext=bar"