services:
  fastapi:
    image: skgif:test
    container_name: fastapi
    hostname: fastapi
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - "./app.py:/app/app.py"
      - "./config.toml:/app/config.toml"
      - "./merge:/app/merge"

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - "./nginx/merge/API/core:/usr/share/nginx/html:ro"
